version: "3.7"

services:
  rmlmapper:
    container_name: rmlmapper-webapi
    build: https://github.com/RMLio/rmlmapper-webapi-js.git
    expose:
      - 4000
    restart: always
    networks:
      - rdfconverter_net

  flask:
    container_name: flask
    build: .
    volumes:
      - .:/app
    ports:
      - 5003:5000
    restart: always
    networks:
      - rdfconverter_net

networks:
  rdfconverter_net:
    driver: bridge
