version: "3.7"

services:
  yarrrml-parser:
    environment:
      - PORT=${PARSER_PORT}
    image: ghcr.io/mat-o-lab/yarrrml-parser:v.1.0.2
    expose:
      - ${PARSER_PORT}
    restart: always
    networks:
      - rdfconverter_net

  rmlmapper:
    # changing port doesnt work - issue on rmlmapper side
    environment:
      - PORT=${MAPPER_PORT}
    container_name: rmlmapper-webapi
    image: ghcr.io/mat-o-lab/rmlmapper-webapi:latest
    expose:
      - ${MAPPER_PORT}
    restart: always
    networks:
      - rdfconverter_net

  rdfconverter:
    env_file:
     - .env
    container_name: rdfconverter
    image: ghcr.io/mat-o-lab/rdfconverter:latest
    ports:
      - ${APP_PORT}:${CONVERTER_PORT}
    restart: always
    networks:
      - rdfconverter_net

networks:
  rdfconverter_net:
    name: rdfconverter_net
    driver: bridge
