version: "3.7"

services:
  yarrrml-parser:
    image: ghcr.io/mat-o-lab/yarrrml-parser:latest
    expose:
      - 3000
    restart: always
    networks:
      - rdfconverter_net

  rmlmapper:
    container_name: rmlmapper-webapi
    image: ghcr.io/mat-o-lab/rmlmapper-webapi:latest
    expose:
      - 4000
    restart: always
    networks:
      - rdfconverter_net

  rdfconverter:
    container_name: rdfconverter
    build: .
    #volumes:
    #  - .:/app
    ports:
      - 5003:5000
    restart: always
    networks:
      - rdfconverter_net

networks:
  rdfconverter_net:
    driver: bridge
