version: "3.7"

services:
  yarrrml-parser:
    environment:
      - PORT=${PARSER_PORT}
    image: ghcr.io/mat-o-lab/yarrrml-parser:v.1.0.2
    expose:
      - ${PARSER_PORT}
    restart: always
    networks:
      - rdfconverter_net

  rmlmapper:
    # changing port doesnt work - issue on rmlmapper side
    environment:
      - PORT=${MAPPER_PORT}
    container_name: rmlmapper-webapi1
    image: ghcr.io/mat-o-lab/rmlmapper-webapi:latest
    expose:
      - ${MAPPER_PORT}
    restart: always
    networks:
      - rdfconverter_net

  rdfconverter:
    environment:
      - PARSER_PORT=${PARSER_PORT}
      - APP_PORT=${APP_PORT}
      - MAPPER_PORT=${MAPPER_PORT}
      - CONVERTER_PORT=${CONVERTER_PORT}
      - APP_SECRET=${APP_SECRET}
      - ADMIN_NAME=${ADMIN_NAME}
      - ADMIN_MAIL=${ADMIN_MAIL}
      - APP_MODE=${APP_MODE}
      - APP_NAME=${APP_NAME}
      - APP_SOURCE=${APP_SOURCE}
    container_name: rdfconverter
    image: ghcr.io/mat-o-lab/rdfconverter:latest
    ports:
      - ${APP_PORT}:${CONVERTER_PORT}
    restart: always
    networks:
      - rdfconverter_net

networks:
  rdfconverter_net:
    name: rdfconverter_net
    driver: bridge
