version: "3.7"

services:
  yarrrml-parser:
    build: ./yarrrml-parser
    expose:
      - 3000
    restart: always
    networks:
      - flask

  rmlmapper:
    container_name: rmlmapper-webapi
    build: ./rmlmapper-webapi
    expose:
      - 4000
    restart: always
    networks:
      - rdfconverter_net

  rdfconverter:
    container_name: rdfconverter
    build: .
    #volumes:
      #- .:/app
    ports:
      - 5003:5000
    restart: always
    networks:
      - rdfconverter_net

networks:
  rdfconverter_net:
    driver: bridge
