version: "3.7"

services:
  yarrrml-parser:
    environment:
      - PORT=${PARSER_PORT}
    #build:
    #  context: ./yarrrml-parser
    #  dockerfile: ./Dockerfile
    image: ghcr.io/mat-o-lab/yarrrml-parser:latest
    expose:
      - ${PARSER_PORT}
    restart: always
    networks:
      - rdfconverter_net

  rmlmapper:
    # changing port doesnt work - issue on rmlmapper side
    environment:
      - PORT=${MAPPER_PORT}
    #build:
    #  context: ./rmlmapper-webapi
    #  dockerfile: ./Dockerfile
    container_name: rmlmapper-webapi
    image: ghcr.io/mat-o-lab/rmlmapper-webapi:latest
    expose:
      - ${MAPPER_PORT}
    restart: always
    networks:
      - rdfconverter_net

  rdfconverter:
    build:
     context: ./
     dockerfile: ./Dockerfile
    environment:
      - PARSER_PORT=${PARSER_PORT}
      - MAPPER_PORT=${MAPPER_PORT}
      - APP_MODE=development
      - PORT=${CONVERTER_PORT}
    container_name: rdfconverter
    image: ghcr.io/mat-o-lab/rdfconverter:latest
    ##not needed in production
    volumes:
      - .:/app
    ports:
      - ${APP_PORT}:${CONVERTER_PORT}
    restart: always
    networks:
      - rdfconverter_net

networks:
  rdfconverter_net:
    name: rdfconverter_net
    driver: bridge
