version: "3.7"

services:
  rmlmapper:
    container_name: rmlmapper-webapi
    build: https://github.com/RMLio/rmlmapper-webapi-js.git
    expose:
      - 4000
    restart: always
    networks:
      - flask

  flask:
    container_name: flask
    build: .
    volumes:
      - .:/app
    ports:
      - 5000:5000
    restart: always
    networks:
      - flask

networks:
  flask:
    name: RDFConverter
    driver: bridge