version: "3.7"

services:
  flask:
    container_name: flask
    build: .
    volumes:
      - .:/app
    ports:
      - 5000:5000
    restart: always
    networks:
      - flask

networks:
  flask:
    name: RDFConverter
    driver: bridge