rdfconverter:
  unittest:
    location:
      host: "http://127.0.0.1"
      port: "5000"
    yarrrml2rml:
      data:
        input: "https://raw.githubusercontent.com/Mat-O-Lab/resources/main/mappings/Zugversuch_eng_ETFE-Ref%252BGroesseneffekt2-map.yaml"
        expectedOutput: "./tests/data//yarrrmltorml/mapping-expected.rml.ttl"
      contextroot: "api/yarrrmltorml"
    joindata:
      data:
        test1:
          input: "https://raw.githubusercontent.com/Mat-O-Lab/resources/main/rdfconverter/tests/joindata/in1.rml.ttl"
          expectedOutput: "https://raw.githubusercontent.com/Mat-O-Lab/resources/main/rdfconverter/tests/joindata/out1.ttl"
        test2:
          input1: "https://raw.githubusercontent.com/Mat-O-Lab/resources/main/rdfconverter/tests/joindata/in1.rml.ttl"
          input2: "https://raw.githubusercontent.com/Mat-O-Lab/resources/main/mechanics/data/polymer_tensile/Zugversuch_eng_ETFE-Ref%2BGroesseneffekt6-metadata.json"
          expectedOutput: "https://raw.githubusercontent.com/Mat-O-Lab/resources/main/rdfconverter/tests/joindata/out2.ttl"
      contextroot: "api/joindata"
    validation:
      data:
        test1:
          shacl: "https://github.com/Mat-O-Lab/resources/raw/main/rdfconverter/tests/validation/shacl1.ttl"
          rdf: "https://github.com/Mat-O-Lab/resources/raw/main/rdfconverter/tests/validation/rdf1.ttl"
        test2:
          shacl: "https://github.com/Mat-O-Lab/resources/raw/main/rdfconverter/tests/validation/shacl1.ttl"
          rdf: "https://github.com/Mat-O-Lab/resources/raw/main/rdfconverter/tests/validation/rdf2.ttl"
      contextroot: "api/rdfvalidator"