name: Build

on:
  push:
    branches:
      - development
jobs:
  run-servlet-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build App
        run: docker-compose -d -f flaskapp/docker-compose.yml up
      - name: Ping App
        run: ping -c1 -W1 localhost:5000